// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwdepjlmluhgoobnvzck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3ZGVwamxtbHVoZ29vYm52emNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMjc2MDgsImV4cCI6MjA2MTgwMzYwOH0.eDk3ULVIQ6j6_EXHMXSGc0ERjTFbOK353YJMNYVz-m8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);